name: shopmate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  path_provider: ^1.2.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.15.8
  jaguar_retrofit: ^2.8.8
  jaguar_serializer: ^2.2.12
  jaguar_cache: ^2.1.2
  validations: ^0.8.3
  cached_network_image: ^1.1.1
  flutter_spinkit: ^3.1.0

  timeago: ^2.0.18
  shared_preferences: ^0.5.3
  equatable: ^0.4.0
  meta: ^1.1.7
  bloc: ^0.14.4
  flutter_bloc: ^0.20.0
  validate: ^1.7.0
  flutter_secure_storage: ^3.2.1+1
  validators: 2.0.0+1
  errors: ^0.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner:
  jaguar_retrofit_gen: ^2.8.6
  jaguar_serializer_cli: ^2.2.5
  validations_generator: ^0.8.3
  intl_translation: ^0.17.5
  flutter_test:
    sdk: flutter
  built_vector: ^0.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: ShopMate
      fonts:
        - asset: fonts/ShopMate.ttf
